### ISSUE TITLE
[Investigate] Cobra Library

### ISSUE THREAD

**Issue by dvonthenen** [deepgram/deepgram-cli#1]
Investigate Cobra (https://github.com/spf13/cobra) - This is pretty much the defacto library used for creating Go CLIs (used by [127k Go projects](https://github.com/spf13/cobra/network/dependents) in GitHub).

Some notable projects to take a look at:
- kubectl (kubernetes CLI) - https://github.com/kubernetes/kubectl/
- docker CLI - https://github.com/docker/cli/

**Comment by lukeocodes** [comment]
Building based on this so closing the issue as completed
